title: Neha Upadhyay's Blog
description: >
  Hi, I am **Neha Upadhyay**, a **Full Stack Developer**.
copyright: Neha Upadhyay
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username:
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "nehaupadhyay12"
feed_icon: rss
email: "connect@neha-upadhyay.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
